
import { Language, IncidentMarker } from './types';

export const VOICE_TRIGGERS = {
  EN: ['help', 'emergency', 'sos', 'guardian'],
  FR: ['aide', 'secours', 'urgence', 'guardian'],
  AR: ['نجدة', 'مساعدة', 'طوارئ', 'عون']
};

export const TEXTS = {
  EN: {
    app_name: "GuardianAI",
    sos: "SOS",
    start_monitoring: "Start Monitoring",
    voice_active: "Voice Guard Active",
    threat_level: "Risk Assessment", 
    persons: "Individuals Detected", 
    vehicles: "Vehicles Detected",
    location: "Location Context",
    generate_report: "Evidence Report",
    download_pdf: "Download Report", 
    back: "Back",
    community_map: "Community Safety Network",
    recent_incidents: "Recent Activity", 
    analyzing: "Analyzing Scene...",
    stop: "STOP MONITORING",
    evidence_captured: "Evidence Secured",
    recording: "RECORDING INCIDENT", 
    safe: "Safe",
    caution: "Caution",
    danger: "High Risk",
    dashboard: "Dashboard",
    history: "Evidence Vault",
    cloud_backup: "Cloud Backup",
    uploading: "Securing Data...",
    secured: "Secured in Drive",
    share_community: "Alert Network",
    share_prompt: "Help locate this device? Share anonymized location data.", 
    sightings: "Activity Reports",
    access_web: "Access Web Portal",
    incident_summary: "Incident Summary",
    alert_sent: "Network Alerted",
    settings: "Smart Protection",
    smart_active: "Monitoring Active",
    auto_trigger: "Auto-Triggered By",
    cancel_alarm: "Cancel Alert",
    clear_evidence: "Clear All Test Evidence",
    confirm_clear: "Are you sure? This will permanently delete all stored evidence. This action cannot be undone.",
    triggers: {
        power: "Power Button Force",
        airplane: "Connection Cutoff",
        sim: "SIM Card Eject",
        movement: "Unusual Movement",
        unlock: "Failed Access",
        geofence: "Zone Exit"
    },
    simulation: "Test Trigger",
    onboarding: {
      welcome: "Welcome to GuardianAI",
      select_lang: "Choose your language",
      voice_setup: "Voice Activation Setup",
      say_phrase: "Say the magic phrase:",
      listening: "Listening...",
      success: "Voice recognized.",
      skip: "Skip for now",
      finish: "Start Protection",
      practice: "Practice"
    },
    demo_mode: "Demo Mode",
    install_app: "Install App",
    contacts: {
        title: "Emergency Contacts",
        add: "Add Contact",
        name: "Name",
        email: "Email",
        phone: "Phone (Optional)",
        relation: "Relationship",
        notified: "Notified Contacts",
        empty: "Add trusted contacts to notify them immediately during an incident."
    },
    classify: {
        title: "Classify Incident",
        lost: "Lost Device",
        unauthorized: "Unauthorized Access",
        emergency: "Emergency"
    },
    security: {
        title: "Vault Security",
        enable_pin: "Protect Vault with PIN",
        set_pin: "Set Security PIN",
        enter_pin: "Enter PIN to Unlock",
        locked: "Vault Locked",
        locked_desc: "Too many failed attempts. Security photo captured.",
        cloud_immutable: "Cloud Backup Active: Evidence cannot be deleted locally.",
        intruder_alert: "📸 Intruder detected",
        delete_confirm: "Delete this evidence?",
        protected: "Protected"
    },
    stealth: {
        title: "Stealth Mode",
        desc: "Silent recording with black screen for theft triggers."
    }
  },
  FR: {
    app_name: "GuardianAI",
    sos: "SOS",
    start_monitoring: "Surveillance Active",
    voice_active: "Garde Vocale Active",
    threat_level: "Niveau de Risque",
    persons: "Individus détectés",
    vehicles: "Véhicules détectés",
    location: "Contexte",
    generate_report: "Rapport de Preuve",
    download_pdf: "Télécharger le Rapport",
    back: "Retour",
    community_map: "Réseau de Sécurité",
    recent_incidents: "Activité Récente",
    analyzing: "Analyse en cours...",
    stop: "ARRÊTER",
    evidence_captured: "Preuve Sécurisée",
    recording: "ENREGISTREMENT",
    safe: "Sûr",
    caution: "Prudence",
    danger: "Risque Élevé",
    dashboard: "Tableau de bord",
    history: "Coffre-fort",
    cloud_backup: "Sauvegarde Cloud",
    uploading: "Sécurisation...",
    secured: "Sécurisé sur Drive",
    share_community: "Alerter le Réseau",
    share_prompt: "Aider à localiser l'appareil ? Partager la position.",
    sightings: "Signalements",
    access_web: "Portail Web",
    incident_summary: "Résumé de l'incident",
    alert_sent: "Alerte envoyée",
    settings: "Protection Intelligente",
    smart_active: "Protection Active",
    auto_trigger: "Déclenchement Auto",
    cancel_alarm: "Annuler Alerte",
    clear_evidence: "Effacer les preuves de test",
    confirm_clear: "Êtes-vous sûr ? Cela supprimera définitivement toutes les preuves stockées.",
    triggers: {
        power: "Bouton Power Forcé",
        airplane: "Coupure Connexion",
        sim: "Éjection SIM",
        movement: "Mouvement Suspect",
        unlock: "Accès Échoué",
        geofence: "Sortie Zone"
    },
    simulation: "Test",
    onboarding: {
      welcome: "Bienvenue sur GuardianAI",
      select_lang: "Choisissez votre langue",
      voice_setup: "Configuration Vocale",
      say_phrase: "Dites la phrase magique :",
      listening: "Écoute en cours...",
      success: "Voix reconnue.",
      skip: "Passer",
      finish: "Démarrer",
      practice: "S'entraîner"
    },
    demo_mode: "Mode Démo",
    install_app: "Installer l'app",
    contacts: {
        title: "Contacts d'Urgence",
        add: "Ajouter Contact",
        name: "Nom",
        email: "Email",
        phone: "Téléphone (Optionnel)",
        relation: "Relation",
        notified: "Contacts Notifiés",
        empty: "Ajoutez des contacts de confiance pour les notifier immédiatement."
    },
    classify: {
        title: "Classer l'incident",
        lost: "Appareil Perdu",
        unauthorized: "Accès Non Autorisé",
        emergency: "Urgence"
    },
    security: {
        title: "Sécurité du Coffre",
        enable_pin: "Protéger par PIN",
        set_pin: "Définir le PIN",
        enter_pin: "Entrer PIN pour déverrouiller",
        locked: "Coffre Verrouillé",
        locked_desc: "Trop de tentatives. Photo de sécurité capturée.",
        cloud_immutable: "Sauvegarde Cloud Active : Suppression locale impossible.",
        intruder_alert: "📸 Intrus détecté",
        delete_confirm: "Supprimer cette preuve ?",
        protected: "Protégé"
    },
    stealth: {
        title: "Mode Furtif",
        desc: "Enregistrement silencieux avec écran noir pour le vol."
    }
  },
  AR: {
    app_name: "GuardianAI",
    sos: "نجدة",
    start_monitoring: "بدء المراقبة",
    voice_active: "الحماية الصوتية نشطة",
    threat_level: "تقييم المخاطر",
    persons: "الأفراد المكتشفين",
    vehicles: "المركبات المكتشفة",
    location: "سياق الموقع",
    generate_report: "تقرير الأدلة",
    download_pdf: "تحميل التقرير",
    back: "عودة",
    community_map: "شبكة الأمان",
    recent_incidents: "النشاط الأخير",
    analyzing: "جاري التحليل...",
    stop: "إيقاف المراقبة",
    evidence_captured: "تم تأمين الدليل",
    recording: "تسجيل الحادث",
    safe: "آمن",
    caution: "حذر",
    danger: "خطر مرتفع",
    dashboard: "لوحة القيادة",
    history: "خزنة الأدلة",
    cloud_backup: "نسخ احتياطي",
    uploading: "جاري التأمين...",
    secured: "مؤمن في السحابة",
    share_community: "تنبيه الشبكة",
    share_prompt: "المساعدة في تحديد موقع الجهاز؟ مشاركة الموقع.",
    sightings: "البلاغات",
    access_web: "البوابة الإلكترونية",
    incident_summary: "ملخص الحادث",
    alert_sent: "تم الإرسال",
    settings: "الحماية الذكية",
    smart_active: "الحماية نشطة",
    auto_trigger: "تشغيل تلقائي",
    cancel_alarm: "إلغاء التنبيه",
    clear_evidence: "مسح جميع أدلة الاختبار",
    confirm_clear: "هل أنت متأكد؟ سيؤدي هذا إلى حذف جميع الأدلة المخزنة بشكل دائم.",
    triggers: {
        power: "زر التشغيل",
        airplane: "قطع الاتصال",
        sim: "إخراج الشريحة",
        movement: "حركة غير معتادة",
        unlock: "فشل الدخول",
        geofence: "مغادرة المنطقة"
    },
    simulation: "تجربة",
    onboarding: {
      welcome: "مرحباً بك في GuardianAI",
      select_lang: "اختر لغتك",
      voice_setup: "إعداد التفعيل الصوتي",
      say_phrase: "قل العبارة السحرية:",
      listening: "جاري الاستماع...",
      success: "تم التعرف على الصوت.",
      skip: "تخطي",
      finish: "بدء الحماية",
      practice: "تدريب"
    },
    demo_mode: "وضع العرض",
    install_app: "تثبيت التطبيق",
    contacts: {
        title: "جهات اتصال الطوارئ",
        add: "إضافة جهة اتصال",
        name: "الاسم",
        email: "البريد الإلكتروني",
        phone: "الهاتف (اختياري)",
        relation: "العلاقة",
        notified: "تم إبلاغ",
        empty: "أضف جهات اتصال موثوقة لإبلاغهم فوراً عند وقوع حادث."
    },
    classify: {
        title: "تصنيف الحادث",
        lost: "جهاز مفقود",
        unauthorized: "دخول غير مصرح به",
        emergency: "حالة طوارئ"
    },
    security: {
        title: "أمان الخزنة",
        enable_pin: "حماية برمز PIN",
        set_pin: "تعيين رمز PIN",
        enter_pin: "أدخل الرمز لفتح القفل",
        locked: "الخزنة مقفلة",
        locked_desc: "محاولات خاطئة كثيرة. تم التقاط صورة.",
        cloud_immutable: "النسخ الاحتياطي نشط: لا يمكن حذف الأدلة محلياً.",
        intruder_alert: "📸 تم كشف متسلل",
        delete_confirm: "حذف هذا الدليل؟",
        protected: "محمي"
    },
    stealth: {
        title: "الوضع الخفي",
        desc: "تسجيل صامت مع شاشة سوداء لحالات السرقة."
    }
  }
};

export const MOCK_INCIDENTS: IncidentMarker[] = [
  { id: '1', lat: 36.75, lng: 3.05, type: 'Theft', description: 'Unauthorized access detected', time: '10 min ago' },
  { id: '2', lat: 36.76, lng: 3.06, type: 'Sighting', description: 'Person of interest seen', time: '5 min ago' },
  { id: '3', lat: 36.74, lng: 3.04, type: 'Suspicious', description: 'Unusual activity reported', time: '2 hrs ago' },
];
